// <auto-generated/>
// This file replaces the XAML markup compiler output (App.g.cs) that cannot run
// under the .NET 8 SDK because Windows App SDK 1.7's compiler depends on
// System.Reflection.Adds.MetadataDispenser (a .NET Framework-only API).
// The XAML compiler is disabled via EnableDefaultApplicationDefinition=false in the .csproj.

#pragma warning disable 1008
#pragma warning disable 1128
#pragma warning disable 1821

using System;
using Microsoft.UI.Xaml;

namespace LyconWindows
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler", "3.0.0.0")]
    public partial class App
    {
        private bool _contentLoaded;

        [global::System.STAThread()]
        public static void Main(string[] args)
        {
            // app.Run() is a WPF API that does not exist in WinUI 3 / Windows App SDK.
            // Application.Start is the WinUI 3 entry point: it takes a callback that
            // creates the Application instance and kicks off the dispatcher.
            Application.Start(_ => { var app = new App(); });
        }

        public void InitializeComponent()
        {
            if (_contentLoaded) return;
            _contentLoaded = true;
            var resourceLocator = new Uri("ms-appx:///App.xaml");
            Application.LoadComponent(this, resourceLocator);
        }
    }
}

#pragma warning restore 1008
#pragma warning restore 1128
#pragma warning restore 1821
