// <auto-generated/>
// This file replaces the XAML markup compiler output (MainWindow.g.i.cs) that cannot run
// under the .NET 8 SDK because Windows App SDK 1.7's compiler depends on
// System.Reflection.Adds.MetadataDispenser (a .NET Framework-only API).

#pragma warning disable 1008
#pragma warning disable 1128
#pragma warning disable 1821

using System;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;

namespace LyconWindows
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler", "3.0.0.0")]
    public partial class MainWindow
    {
        private bool _contentLoaded;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler", "3.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.UI.Xaml.Controls.WebView2 BrowserWebView { get; private set; }

        public void InitializeComponent()
        {
            if (_contentLoaded) return;
            _contentLoaded = true;
            var resourceLocator = new Uri("ms-appx:///MainWindow.xaml");
            Application.LoadComponent(this, resourceLocator);
            // WinUI 3 Window does not expose FindName (that API lives on FrameworkElement).
            // After LoadComponent the root XAML element is assigned to Window.Content; we
            // can search its name scope to wire up the x:Name field, mirroring the compiler-
            // generated code that the markup compiler would normally emit.
            if (this.Content is FrameworkElement root)
                BrowserWebView = (WebView2)root.FindName("BrowserWebView");
        }
    }
}

#pragma warning restore 1008
#pragma warning restore 1128
#pragma warning restore 1821
