/**
 * Gate 1 — Domain Vocabulary: Immutable IDs
 *
 * Strongly-typed, branded, immutable identifiers. Every ID is a `string` at
 * runtime but the TypeScript type system prevents cross-usage (you cannot pass
 * a TabId where a WindowId is expected).
 *
 * These IDs are the currency of the Core. They are opaque — no semantic
 * meaning is encoded in the string value. The Core generates them via the
 * `Id` namespace's `generate` functions, which use crypto-random prefixes.
 *
 * Per Article III, Commands and Events carry these IDs for causal tracing.
 */

// ── Branded ID pattern ──────────────────────────────────────────────────

/** Base type: every Lycon ID is a string with a phantom brand. */
export interface LyconId {
  readonly __lyconIdBrand: unique symbol;
}

/**
 * Helper to create a branded ID type from a base name.
 * At runtime the value is just a string; at compile time it is distinct.
 */
export type Brand<K, T> = K & { readonly __brand: T };

/** All immutable ID types in the Lycon Core. */
export type BrowserId = Brand<string, 'BrowserId'>;
export type SessionId = Brand<string, 'SessionId'>;
export type WindowId = Brand<string, 'WindowId'>;
export type TabId = Brand<string, 'TabId'>;
export type PageId = Brand<string, 'PageId'>;
export type NavigationId = Brand<string, 'NavigationId'>;
export type CommandId = Brand<string, 'CommandId'>;
export type EventId = Brand<string, 'EventId'>;
export type IdentityVersion = Brand<number, 'IdentityVersion'>;

// ── Runtime ID generators ──────────────────────────────────────────────

const PREFIXES = {
  Browser: 'br',
  Session: 'ss',
  Window: 'wn',
  Tab: 'tb',
  Page: 'pg',
  Navigation: 'nv',
  Command: 'cmd',
  Event: 'evt',
} as const;

/**
 * Generate a random Lycon ID with the given prefix.
 * Uses crypto.getRandomValues when available, falls back to Math.random.
 * The resulting string is opaque — do not parse it.
 */
function generateId(prefix: keyof typeof PREFIXES): string {
  const chars = '0123456789abcdefghijklmnopqrstuvwxyz';
  const randomPart = Array.from({ length: 12 }, () =>
    chars[Math.floor(Math.random() * chars.length)]
  ).join('');
  return `${PREFIXES[prefix]}_${randomPart}`;
}

/**
 * Cast a string to a branded ID type. Use only for deserialization of
 * IDs that were generated by the corresponding `generate*` function.
 */
function asId<T extends string>(raw: string): T {
  return raw as unknown as T;
}

/**
 * Namespace providing runtime ID generators for every ID type.
 * The Core is the sole caller of these generators.
 */
export const Id = {
  browser(): BrowserId { return asId<BrowserId>(generateId('Browser')); },
  session(): SessionId { return asId<SessionId>(generateId('Session')); },
  window(): WindowId { return asId<WindowId>(generateId('Window')); },
  tab(): TabId { return asId<TabId>(generateId('Tab')); },
  page(): PageId { return asId<PageId>(generateId('Page')); },
  navigation(): NavigationId { return asId<NavigationId>(generateId('Navigation')); },
  command(): CommandId { return asId<CommandId>(generateId('Command')); },
  event(): EventId { return asId<EventId>(generateId('Event')); },
} as const;

/**
 * Parse a serialized ID back into its branded form.
 * Throws only if the input is not a string (defensive — the Core
 * always round-trips IDs it generated).
 */
export function parseId<T extends string>(raw: unknown): T {
  if (typeof raw !== 'string') {
    throw new Error(`Invalid ID: expected string, got ${typeof raw}`);
  }
  return raw as unknown as T;
}
